# ─────────────────────────────────────────────────────────────────
# Archivo: .streamlit/secrets.toml
# Ubicación: crea la carpeta .streamlit/ en la raíz de tu proyecto
# y guarda este archivo ahí.
# ─────────────────────────────────────────────────────────────────

[email]
sender   = "adminfs01@gmail.com"       # Correo Gmail desde donde se enviarán los códigos
password = "pbcq tyas port hnjl"     # Contraseña de aplicación Gmail (NO tu contraseña normal)


